# Generated by Django 2.2.3 on 2020-03-13 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_auto_20200314_0034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='file',
            new_name='Files',
        ),
    ]
